apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nameofmirror-pvc
  namespace: namespace
spec:
  storageClassName: storageclassname
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi