apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nameofrepo-pvc
  namespace: namespacetemplate
spec:
  storageClassName: storageclassnamex
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi