apiVersion: v1
kind: Service
metadata:
  name: rmn-api
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: rmn-api

---

apiVersion: v1
kind: Service
metadata:
  name: rmn-wui
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: rmn-wui