apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: repositorymanagernet
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: "repositories.pajdisek.palocal"
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: registrymanagernetapi
            port:
              number: 80
      - path: /webui(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: registrymanagernetwebui
            port:
              number: 80