apiVersion: batch/v1
kind: Job
metadata:
  name: databasedeployment
  namespace: repositorymanagernet
spec:
  template:
    spec:
      containers:
      - name: dbdeploy
        image: ghcr.io/bigpod98/databasedeployment:latest
        command: ["/opt/databaseDeployment/databaseDeployment", "--env-var"]
        env:
        - name: MYSQL_DATABASE_NAME
          value: "repositorymanagernet"
        - name: MYSQL_USERNAME
          value: "rmn"
        - name: MYSQL_PASSWORD
          value: "repositorymanagernet"
        - name: MYSQL_IP
          value: "mysql.mysql-database.svc.cluster.local"
        - name: MYSQL_PORT
          value: "3306"
      restartPolicy: Never
  backoffLimit: 4