apiVersion: v1
kind: Service
metadata:
  name: repositorymanagernetapi
  namespace: repositorymanagernet
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: rmn-api

---

apiVersion: v1
kind: Service
metadata:
  name: repositorymanagernetwebui
  namespace: repositorymanagernet
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: rmn-wui

---

apiVersion: v1
kind: Service
metadata:
  name: repositorymanagernetuploadapi
  namespace: repositorymanagernet
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: rmn-uploadapi